### ISSUE TITLE
gpt API

### ISSUE THREAD

**Issue by Yqao** [ppisljar/pdf_translator#4]
可以使用中转的API嘛？不使用apenai官方的API？

**Comment by ppisljar** [comment]
I am not familiar with transit API, probably it would require some modifications to the code.

**Comment by colin4k** [comment]
> 可以使用中转的API嘛？不使用apenai官方的API？

可以，修改openai_gpt.py
`self.client = OpenAI(api_key=cfg['openai_api_key'],base_url=cfg['base_url'])`
然后在config.yaml中增加：
```
translator:
  type: openai
  openai_api_key: 'sk-xxx'
  base_url: 'http://xxx.xxx/v1'
```
